//! Code generation: IR → Rust source code.
//!
//! The main entry point is [`generate`], which takes a parsed IR [`Module`]
//! and produces formatted Rust source code as a string.

pub mod classes;
pub mod discriminated_unions;
pub mod enums;
pub mod functions;
pub mod signatures;
pub mod subtyping;
pub mod typemap;

use proc_macro2::TokenStream;
use quote::quote;

use crate::ir::{InterfaceClassification, Module, TypeDeclaration, TypeKind, TypeRef};
use crate::parse::scope::ScopeId;

use typemap::CodegenContext;

/// Convert an optional doc string into `/// ...` doc-comment attributes.
///
/// Returns an empty `TokenStream` if `doc` is `None`.
pub(crate) fn doc_tokens(doc: &Option<String>) -> TokenStream {
    match doc {
        Some(text) => {
            let lines: Vec<TokenStream> = text
                .lines()
                .map(|line| {
                    // Non-empty lines get a leading space so the rendered
                    // doc reads `/// foo` rather than `///foo`. Empty
                    // lines stay bare so blank-line separators don't
                    // emit as a stray `#[doc = " "]`.
                    let line = if line.is_empty() {
                        String::new()
                    } else {
                        format!(" {line}")
                    };
                    quote! { #[doc = #line] }
                })
                .collect();
            quote! { #(#lines)* }
        }
        None => quote! {},
    }
}

/// Options for controlling code generation output.
#[derive(Debug, Clone, Default)]
pub struct GenerateOptions {
    /// When `true`, the default error type for fallible bindings
    /// (`@throws`-less callables that catch JS exceptions) is
    /// `js_sys::Error` rather than `JsValue`. Bindings whose
    /// `@throws` JSDoc names a specific type still use that type.
    ///
    /// Useful in environments that prefer the typed `Error` API
    /// (`message`, `name`, `cause`, …) over raw `JsValue`. The
    /// trade-off is that JS code returning a non-Error throwable
    /// (e.g. `throw "oops"`) now produces a runtime conversion
    /// error rather than the silent `JsValue` pass-through.
    pub errors_as_error: bool,
}

/// Generate Rust source code from a parsed IR module + global context.
///
/// Returns the formatted source as a string, ready to be written to a file.
pub fn generate(module: &Module, gctx: &crate::context::GlobalContext) -> anyhow::Result<String> {
    generate_with_options(module, gctx, &GenerateOptions::default())
}

/// Generate Rust source code with explicit options.
pub fn generate_with_options(
    module: &Module,
    gctx: &crate::context::GlobalContext,
    options: &GenerateOptions,
) -> anyhow::Result<String> {
    let tokens = generate_tokens(module, gctx, options);
    // Validate that the tokens are valid Rust syntax.
    syn::parse2::<syn::File>(tokens.clone()).map_err(|e| {
        anyhow::anyhow!("generated tokens are not valid syn:\n{e}\n\nTokens:\n{tokens}")
    })?;
    let formatted = rustfmt(&tokens.to_string())?;
    // Prepend a header comment. Line comments don't survive `quote!`
    // token generation, so they have to be emitted as plain text
    // after formatting.
    Ok(format!(
        "// Generated by ts-gen. Do not edit.\n\n{formatted}"
    ))
}

/// Format Rust source via `rustfmt`.
///
/// Falls back to `prettyplease` if `rustfmt` is not available.
fn rustfmt(code: &str) -> anyhow::Result<String> {
    use std::io::Write;
    use std::process::{Command, Stdio};

    let mut child = match Command::new("rustfmt")
        .arg("--edition=2021")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
    {
        Ok(child) => child,
        Err(_) => {
            let file = syn::parse_str::<syn::File>(code)?;
            return Ok(prettyplease::unparse(&file));
        }
    };

    child.stdin.take().unwrap().write_all(code.as_bytes())?;

    let output = child.wait_with_output()?;
    if output.status.success() {
        Ok(String::from_utf8(output.stdout)?)
    } else {
        let file = syn::parse_str::<syn::File>(code)?;
        Ok(prettyplease::unparse(&file))
    }
}

/// Generate the token stream for a full module.
///
/// `Promise<T>` awaitability used to require an emitted `PromiseExt` trait
/// (orphan rule prevented an `IntoFuture` impl from generated code), but
/// upstream `js_sys` now implements `IntoFuture` for `Promise<T>` directly,
/// so callers get `.await` for free without anything generated here.
fn generate_tokens(
    module: &Module,
    gctx: &crate::context::GlobalContext,
    options: &GenerateOptions,
) -> TokenStream {
    let cgctx = CodegenContext::from_module_with_options(module, gctx, options.errors_as_error);

    let preamble = quote! {
        #[allow(unused_imports)]
        use wasm_bindgen::prelude::*;
        #[allow(unused_imports)]
        use js_sys::*;
    };

    // Group declarations by module context.
    // Global declarations go at the top level.
    // Module declarations go inside `mod <name> { ... }` blocks.
    let mut global_items = Vec::new();
    let mut module_items: std::collections::BTreeMap<std::rc::Rc<str>, Vec<TokenStream>> =
        std::collections::BTreeMap::new();

    for &type_id in &module.types {
        let decl = gctx.get_type(type_id);
        if let Some(tokens) = generate_declaration(decl, &cgctx) {
            match &decl.module_context {
                crate::ir::ModuleContext::Global => {
                    global_items.push(tokens);
                }
                crate::ir::ModuleContext::Module(m) => {
                    module_items.entry(m.clone()).or_default().push(tokens);
                }
            }
        }
    }

    // Wrap each module's items in a `mod` block
    let mod_blocks: Vec<TokenStream> = module_items
        .into_iter()
        .map(|(mod_specifier, items)| {
            let mod_name = typemap::make_ident(&crate::util::naming::module_specifier_to_ident(
                &mod_specifier,
            ));
            quote! {
                pub mod #mod_name {
                    use wasm_bindgen::prelude::*;
                    use js_sys::*;
                    use super::*;
                    #(#items)*
                }
            }
        })
        .collect();

    // External type use aliases (collected during codegen above)
    let external_uses = cgctx.external_use_tokens();

    // Dynamic-union enums synthesised during the per-declaration
    // emit pass. Emitted at the global scope; references inside
    // each enum already resolve through the regular `to_syn_type`
    // lowering, so cross-module member types are emitted with the
    // appropriate path qualifier (`module_name::TypeName`).
    let dynamic_unions = generate_dynamic_unions(&cgctx);

    // Emit codegen diagnostics
    cgctx.take_diagnostics().emit();

    quote! {
        #preamble
        #external_uses
        #(#global_items)*
        #(#mod_blocks)*
        #dynamic_unions
    }
}

/// Emit the synthesised dynamic-union enums collected on `cgctx`
/// during the per-declaration pass. Each enum lowers each member
/// type via the regular return-position path, so cross-module
/// references get the correct path qualifier.
fn generate_dynamic_unions(cgctx: &CodegenContext) -> TokenStream {
    use crate::ir::ModuleContext;
    use crate::ir::TypeRef as T;
    let registry = cgctx.dynamic_unions.borrow();
    if registry.by_key.is_empty() {
        return quote! {};
    }
    let from_module = ModuleContext::Global;
    let enums: Vec<TokenStream> = registry
        .by_key
        .values()
        .map(|info| {
            let enum_ident = typemap::make_ident(&info.rust_name);
            // Track variant names within a single enum so that a
            // `string` arm doesn't collide with another arm whose
            // payload also lowers to `String`. First-seen wins; the
            // second is numbered.
            let mut used_variants: std::collections::HashSet<String> =
                std::collections::HashSet::new();
            let mut alloc_variant = |base: &str| -> String {
                if used_variants.insert(base.to_string()) {
                    return base.to_string();
                }
                let mut i: u32 = 2;
                loop {
                    let candidate = format!("{base}{i}");
                    if used_variants.insert(candidate.clone()) {
                        return candidate;
                    }
                    i += 1;
                }
            };
            let variants: Vec<TokenStream> = info
                .members
                .iter()
                .map(|m| {
                    match m {
                        // String / number / boolean literal members
                        // become string-discriminant / numeric-discriminant
                        // / boolean-discriminant variants — wasm-bindgen
                        // routes these as the literal value at the FFI
                        // boundary, exactly matching TS narrowing.
                        T::StringLiteral(s) => {
                            let variant_name =
                                alloc_variant(&crate::util::naming::to_pascal_case(s));
                            let variant_ident = typemap::make_ident(&variant_name);
                            quote! { #variant_ident = #s }
                        }
                        T::NumberLiteral(n) => {
                            let variant_name = alloc_variant(&format!(
                                "N{}",
                                n.to_string().replace(['.', '-'], "_")
                            ));
                            let variant_ident = typemap::make_ident(&variant_name);
                            // wasm-bindgen accepts integer literals on
                            // numeric-discriminant variants.
                            let lit = syn::LitInt::new(
                                &(*n as i64).to_string(),
                                proc_macro2::Span::call_site(),
                            );
                            quote! { #variant_ident = #lit }
                        }
                        T::BooleanLiteral(b) => {
                            let variant_name = alloc_variant(if *b { "True" } else { "False" });
                            let variant_ident = typemap::make_ident(&variant_name);
                            // Boolean literals don't have a syntactic
                            // discriminant form in Rust enums, so we
                            // fall back to the `1` / `0` numeric
                            // form that wasm-bindgen also recognises.
                            let lit = syn::LitInt::new(
                                if *b { "1" } else { "0" },
                                proc_macro2::Span::call_site(),
                            );
                            quote! { #variant_ident = #lit }
                        }
                        _ => {
                            let variant_name = alloc_variant(&dynamic_union_variant_name(m));
                            let variant_ident = typemap::make_ident(&variant_name);
                            let payload = typemap::to_syn_type(
                                m,
                                typemap::TypePosition::RETURN,
                                Some(cgctx),
                                cgctx.root_scope,
                                &from_module,
                            );
                            quote! { #variant_ident(#payload) }
                        }
                    }
                })
                .collect();
            quote! {
                #[wasm_bindgen]
                pub enum #enum_ident {
                    #(#variants),*
                }
            }
        })
        .collect();
    quote! { #(#enums)* }
}

/// Pick a Rust variant name for a `TypeRef` member of a synthesised
/// dynamic union.
///
/// Variants are named after the **Rust payload type** rather than
/// the TypeScript spelling, so the rendered enum reads consistently:
///
/// ```rust,ignore
/// pub enum ContentKind {
///     String(String),
///     F64(f64),
///     Bool(bool),
///     ArrayBuffer(ArrayBuffer),
///     Uint8Array(Uint8Array),    // not `ArrayBufferView` — that's the TS spelling
/// }
/// ```
///
/// The mapping mirrors `to_syn_type` at return position:
///
/// | TypeScript        | Rust (return)   | Variant name    |
/// | ----------------- | --------------- | --------------- |
/// | `string`          | `String`        | `String`        |
/// | `number`          | `f64`           | `F64`           |
/// | `bigint`          | `BigInt`        | `BigInt`        |
/// | `boolean`         | `bool`          | `Bool`          |
/// | `ArrayBufferView` | `Uint8Array`    | `Uint8Array`    |
/// | `Foo` (named)     | `Foo`           | `Foo`           |
fn dynamic_union_variant_name(ty: &TypeRef) -> String {
    use crate::ir::TypeRef as T;
    use crate::util::naming::to_pascal_case;
    match ty {
        T::Boolean | T::BooleanLiteral(_) => "Bool".to_string(),
        T::Number | T::NumberLiteral(_) => "F64".to_string(),
        T::String | T::StringLiteral(_) => "String".to_string(),
        T::BigInt => "BigInt".to_string(),
        T::Void | T::Undefined => "Undefined".to_string(),
        T::Null => "Null".to_string(),
        T::Any | T::Unknown => "JsValue".to_string(),
        T::Object => "Object".to_string(),
        T::Symbol => "JsValue".to_string(),
        // Return-position lowering specialises `ArrayBufferView` to
        // `Uint8Array` (see `to_syn_type`), so the variant name
        // matches the payload.
        T::ArrayBufferView => "Uint8Array".to_string(),
        // `Array<T>` / `T[]` lowers to `Vec<T>` in return position.
        T::Array(inner) => format!("VecOf{}", dynamic_union_variant_name(inner)),
        T::Nullable(inner) => format!("Optional{}", dynamic_union_variant_name(inner)),
        T::Reference { segments, .. } => {
            // Use the last segment for qualified paths.
            to_pascal_case(segments.last().map(|s| s.as_str()).unwrap_or("Unknown"))
        }
        T::Tuple(_) => "Tuple".to_string(),
        T::Union(_) => "JsValue".to_string(),
        T::Intersection(_) => "JsValue".to_string(),
        T::Function(_) => "Function".to_string(),
        T::Unresolved(_) => "JsValue".to_string(),
    }
}

/// Generate tokens for a single declaration.
fn generate_declaration(decl: &TypeDeclaration, cgctx: &CodegenContext) -> Option<TokenStream> {
    match &decl.kind {
        TypeKind::Class(c) => Some(classes::generate_class(
            c,
            &decl.module_context,
            Some(cgctx),
            decl.scope_id,
        )),
        TypeKind::Interface(i) => match i.classification {
            InterfaceClassification::ClassLike | InterfaceClassification::Unclassified => {
                Some(classes::generate_class_like_interface(
                    i,
                    &decl.module_context,
                    Some(cgctx),
                    None,
                    decl.scope_id,
                ))
            }
            InterfaceClassification::Dictionary => Some(classes::generate_dictionary_extern(
                i,
                &decl.module_context,
                Some(cgctx),
                None,
                decl.scope_id,
            )),
        },
        TypeKind::DiscriminatedUnion(d) => {
            Some(discriminated_unions::generate_discriminated_union(
                d,
                &decl.module_context,
                Some(cgctx),
                decl.scope_id,
            ))
        }
        TypeKind::StringEnum(e) => Some(enums::generate_string_enum(e)),
        TypeKind::NumericEnum(e) => Some(enums::generate_numeric_enum(e)),
        TypeKind::Function(f) => Some(functions::generate_function(
            f,
            &decl.module_context,
            Some(cgctx),
            &decl.doc,
            decl.scope_id,
        )),
        TypeKind::Variable(v) => Some(functions::generate_variable(
            v,
            &decl.module_context,
            Some(cgctx),
            &decl.doc,
            None,
            decl.scope_id,
        )),
        TypeKind::TypeAlias(alias) => Some(generate_type_alias(
            alias,
            cgctx,
            decl.scope_id,
            &decl.module_context,
        )),
        TypeKind::Namespace(ns) => Some(generate_namespace(ns, &decl.module_context, cgctx)),
    }
}

/// Generate output for a TypeAlias declaration.
///
/// - Local alias: `pub type WritableStream = Writable;`
/// - External re-export: `pub use external_crate::Foo;`
fn generate_type_alias(
    alias: &crate::ir::TypeAliasDecl,
    cgctx: &CodegenContext,
    scope: ScopeId,
    from_module: &crate::ir::ModuleContext,
) -> TokenStream {
    if let Some(ref module) = alias.from_module {
        // External re-export: resolve through external map. The
        // target name is the bare ident from the alias target if
        // available, otherwise the alias name itself.
        let type_name = alias.target.as_ident().unwrap_or(alias.name.as_str());
        if let Some(rust_path) = cgctx.resolve_external(type_name, module) {
            let path: syn::Path = syn::parse_str(&rust_path.path).unwrap_or_else(|_| {
                syn::Path::from(syn::Ident::new("JsValue", proc_macro2::Span::call_site()))
            });
            let name = typemap::make_ident(&alias.name);
            if alias.name == type_name {
                return quote! { pub use #path; };
            } else {
                return quote! { pub use #path as #name; };
            }
        }
        cgctx.warn(format!(
            "No external mapping for `{}` from \"{module}\" — emitting JsValue alias",
            type_name,
        ));
        let name = typemap::make_ident(&alias.name);
        return quote! {
            #[allow(dead_code)]
            pub type #name = JsValue;
        };
    }

    // Local alias — only emit if the target resolves to a known type.
    // We only inspect bare references here; generic instantiations
    // and qualified paths flow through to `to_syn_type` unchanged.
    if let Some(target_name) = alias.target.as_ident() {
        if !cgctx.local_types.contains_key(target_name)
            && !crate::codegen::typemap::JS_SYS_RESERVED.contains(&target_name)
        {
            cgctx.warn(format!(
                "Type alias `{}` targets unknown type `{target_name}`, skipping",
                alias.name
            ));
            return quote! {};
        }
    }

    // Resolve the target inside the alias's body scope so its own
    // type parameters bind locally (the alias is a scope-introducing
    // construct in TS).
    let target = typemap::to_syn_type(
        &alias.target,
        typemap::TypePosition::ARGUMENT.to_inner(),
        Some(cgctx),
        alias.body_scope,
        from_module,
    );
    let name = typemap::make_ident(&alias.name);

    // Identity — skip.
    if target.to_string() == alias.name {
        return quote! {};
    }

    // Type-parameter declaration so aliases that mention generics
    // survive codegen: `pub type Handler<Env, Props> = …;` rather
    // than the bare `Handler = …` that would leave `Props`
    // undeclared. Type aliases use plain `<T, U>` (no `JsGeneric`
    // bound) — they're erased at use-site monomorphisation.
    let generics = if alias.type_params.is_empty() {
        quote! {}
    } else {
        let idents = alias
            .type_params
            .iter()
            .map(|tp| typemap::make_ident(&tp.name))
            .collect::<Vec<_>>();
        quote! { <#(#idents),*> }
    };

    let _ = scope;
    quote! {
        #[allow(dead_code)]
        pub type #name #generics = #target;
    }
}

/// Generate a Rust `mod` block for a namespace, with all nested declarations.
fn generate_namespace(
    ns: &crate::ir::NamespaceDecl,
    _parent_ctx: &crate::ir::ModuleContext,
    cgctx: &CodegenContext,
) -> TokenStream {
    let mod_name = typemap::make_ident(&crate::util::naming::to_snake_case(&ns.name));
    let js_name = &ns.name;

    let items: Vec<TokenStream> = ns
        .declarations
        .iter()
        .filter_map(|decl| generate_ns_declaration(decl, js_name, cgctx))
        .collect();

    quote! {
        pub mod #mod_name {
            use wasm_bindgen::prelude::*;
            #(#items)*
        }
    }
}

/// Generate tokens for a declaration inside a namespace.
/// Adds `js_namespace` attribute to extern blocks so wasm_bindgen emits
/// the correct JS access (e.g., `WebAssembly.Module`).
fn generate_ns_declaration(
    decl: &TypeDeclaration,
    ns_js_name: &str,
    cgctx: &CodegenContext,
) -> Option<TokenStream> {
    match &decl.kind {
        TypeKind::Class(c) => Some(classes::generate_class_with_js_namespace(
            c,
            &decl.module_context,
            ns_js_name,
            Some(cgctx),
            decl.scope_id,
        )),
        TypeKind::Interface(i) => match i.classification {
            InterfaceClassification::ClassLike | InterfaceClassification::Unclassified => {
                Some(classes::generate_class_like_interface(
                    i,
                    &decl.module_context,
                    Some(cgctx),
                    Some(ns_js_name),
                    decl.scope_id,
                ))
            }
            InterfaceClassification::Dictionary => Some(classes::generate_dictionary_extern(
                i,
                &decl.module_context,
                Some(cgctx),
                Some(ns_js_name),
                decl.scope_id,
            )),
        },
        TypeKind::DiscriminatedUnion(d) => {
            // Discriminated unions don't currently support `js_namespace`
            // (no observed cases in the wild). Emit without the namespace
            // attribute — if a real case shows up we can thread it
            // through `ClassConfig::js_namespace` like the others.
            Some(discriminated_unions::generate_discriminated_union(
                d,
                &decl.module_context,
                Some(cgctx),
                decl.scope_id,
            ))
        }
        TypeKind::Function(f) => Some(functions::generate_function_with_js_namespace(
            f,
            &decl.module_context,
            ns_js_name,
            Some(cgctx),
            &decl.doc,
            decl.scope_id,
        )),
        TypeKind::StringEnum(e) => Some(enums::generate_string_enum(e)),
        TypeKind::NumericEnum(e) => Some(enums::generate_numeric_enum(e)),
        TypeKind::Variable(v) => Some(functions::generate_variable(
            v,
            &decl.module_context,
            Some(cgctx),
            &decl.doc,
            Some(ns_js_name),
            decl.scope_id,
        )),
        TypeKind::TypeAlias(_) => None,
        TypeKind::Namespace(ns) => Some(generate_namespace(ns, &decl.module_context, cgctx)),
    }
}
