// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Erased;
    #[doc = " Mixed primitives + objects — no LUB, becomes a dynamic union."]
    #[wasm_bindgen(method, getter)]
    pub fn content(this: &Erased) -> ContentKind;
    #[doc = " Inner-erased generic — outer Array stays as `Vec<JsValue>`."]
    #[wasm_bindgen(method, getter)]
    pub fn tags(this: &Erased) -> Vec<JsValue>;
}
impl Erased {
    #[allow(clippy::new_without_default)]
    pub fn new() -> Erased {
        #[allow(unused_unsafe)]
        unsafe {
            JsValue::from(js_sys::Object::new()).unchecked_into()
        }
    }
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type NoErasure;
    #[doc = " Literal widening — lowers to `string`, no enum synthesised."]
    #[wasm_bindgen(method, getter)]
    pub fn variant(this: &NoErasure) -> VariantKind;
    #[doc = " Plain type — no enum synthesised."]
    #[wasm_bindgen(method, getter)]
    pub fn name(this: &NoErasure) -> String;
}
impl NoErasure {
    #[allow(clippy::new_without_default)]
    pub fn new() -> NoErasure {
        #[allow(unused_unsafe)]
        unsafe {
            JsValue::from(js_sys::Object::new()).unchecked_into()
        }
    }
}
#[wasm_bindgen]
extern "C" {
    #[doc = " Async function with an inner-erased Promise — no enum synthesis."]
    #[wasm_bindgen(catch, js_name = "fetchValue")]
    pub async fn fetch_value() -> Result<JsValue, JsValue>;
}
#[wasm_bindgen]
pub enum ContentKind {
    String(String),
    ArrayBuffer(ArrayBuffer),
    Uint8Array(Uint8Array),
}
#[wasm_bindgen]
pub enum VariantKind {
    A = "a",
    B = "b",
}
