// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Foo;
    #[doc = " Plain method — fallible variant uses the new default error type."]
    #[wasm_bindgen(method)]
    pub fn bar(this: &Foo, x: f64) -> String;
    #[doc = " Plain method — fallible variant uses the new default error type."]
    #[wasm_bindgen(method, catch, js_name = "bar")]
    pub fn try_bar(this: &Foo, x: f64) -> Result<String, Error>;
    #[doc = " Async method — `Result<T, Error>` instead of `Result<T, JsValue>`."]
    #[wasm_bindgen(method, catch)]
    pub async fn baz(this: &Foo) -> Result<Number, Error>;
    #[doc = " Method with explicit `@throws` — the typed error wins regardless"]
    #[doc = " of the flag."]
    #[doc = ""]
    #[doc = " ## Errors"]
    #[doc = ""]
    #[doc = " * `TypeError` — when input is invalid"]
    #[wasm_bindgen(method)]
    pub fn parse(this: &Foo, input: &str) -> f64;
    #[doc = " Method with explicit `@throws` — the typed error wins regardless"]
    #[doc = " of the flag."]
    #[doc = ""]
    #[doc = " ## Errors"]
    #[doc = ""]
    #[doc = " * `TypeError` — when input is invalid"]
    #[wasm_bindgen(method, catch, js_name = "parse")]
    pub fn try_parse(this: &Foo, input: &str) -> Result<f64, TypeError>;
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Resource;
    #[doc = " Constructor — wasm-bindgen always catches; default error follows the flag."]
    #[wasm_bindgen(constructor, catch)]
    pub fn new(path: &str) -> Result<Resource, Error>;
}
#[wasm_bindgen]
extern "C" {
    #[doc = " Free function — same default-error rule."]
    #[wasm_bindgen(catch, js_name = "fetchData")]
    pub async fn fetch_data(url: &str) -> Result<JsString, Error>;
}
