// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type DefaultDetails<T: ::wasm_bindgen::JsGeneric>;
    #[wasm_bindgen(method, getter)]
    pub fn value<T: ::wasm_bindgen::JsGeneric>(this: &DefaultDetails<T>) -> T;
    #[wasm_bindgen(method, setter)]
    pub fn set_value<T: ::wasm_bindgen::JsGeneric>(this: &DefaultDetails<T>, val: &T);
}
impl<T: ::wasm_bindgen::JsGeneric> DefaultDetails<T> {
    pub fn new(value: &T) -> DefaultDetails<T> {
        let inner: DefaultDetails<T> = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_value(value);
        inner
    }
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type DefaultFlags;
    #[wasm_bindgen(method, catch, js_name = "getStringDetails")]
    pub async fn get_string_details(
        this: &DefaultFlags,
        default_value: &str,
    ) -> Result<DefaultDetails<JsString>, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getBooleanDetails")]
    pub async fn get_boolean_details(
        this: &DefaultFlags,
        default_value: bool,
    ) -> Result<DefaultDetails<Boolean>, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getNumberDetails")]
    pub async fn get_number_details(
        this: &DefaultFlags,
        default_value: f64,
    ) -> Result<DefaultDetails<Number>, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getStringArray")]
    pub async fn get_string_array(this: &DefaultFlags) -> Result<Array<JsString>, JsValue>;
}
