// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[allow(dead_code)]
pub type Id = JsString;
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type S;
    #[wasm_bindgen(method, getter)]
    pub fn x(this: &S) -> f64;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type S2;
    #[wasm_bindgen(method, getter)]
    pub fn x(this: &S2) -> f64;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "byAlias")]
    pub fn by_alias(id: impl ::wasm_bindgen::JsStringLike) -> String;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "byAlias")]
    pub fn by_alias_js_string(id: impl ::wasm_bindgen::JsStringLike) -> JsString;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "byAlias")]
    pub fn try_by_alias(id: impl ::wasm_bindgen::JsStringLike) -> Result<String, JsValue>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "byAlias")]
    pub fn try_by_alias_js_string(
        id: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<JsString, JsValue>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "asyncByAlias")]
    pub async fn async_by_alias(id: impl ::wasm_bindgen::JsStringLike) -> Result<String, JsValue>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "asyncByAlias")]
    pub async fn async_by_alias_js_string(
        id: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<JsString, JsValue>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "withS")]
    pub fn with_s(s: &S, s2: &S2, name: impl ::wasm_bindgen::JsStringLike);
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "withS")]
    pub fn try_with_s(
        s: &S,
        s2: &S2,
        name: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<(), JsValue>;
}
