// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type ResultBox<T: ::wasm_bindgen::JsGeneric, E: ::wasm_bindgen::JsGeneric>;
    #[wasm_bindgen(method, getter)]
    pub fn value<T: ::wasm_bindgen::JsGeneric, E: ::wasm_bindgen::JsGeneric>(
        this: &ResultBox<T, E>,
    ) -> T;
    #[wasm_bindgen(method, setter)]
    pub fn set_value<T: ::wasm_bindgen::JsGeneric, E: ::wasm_bindgen::JsGeneric>(
        this: &ResultBox<T, E>,
        val: &T,
    );
    #[wasm_bindgen(method, getter)]
    pub fn error<T: ::wasm_bindgen::JsGeneric, E: ::wasm_bindgen::JsGeneric>(
        this: &ResultBox<T, E>,
    ) -> E;
    #[wasm_bindgen(method, setter)]
    pub fn set_error<T: ::wasm_bindgen::JsGeneric, E: ::wasm_bindgen::JsGeneric>(
        this: &ResultBox<T, E>,
        val: &E,
    );
}
impl<T: ::wasm_bindgen::JsGeneric, E: ::wasm_bindgen::JsGeneric> ResultBox<T, E> {
    pub fn new(value: &T, error: &E) -> ResultBox<T, E> {
        let inner: ResultBox<T, E> = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_value(value);
        inner.set_error(error);
        inner
    }
}
