// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type EvaluationDetails<T: ::wasm_bindgen::JsGeneric>;
    #[wasm_bindgen(method, getter, js_name = "flagKey")]
    pub fn flag_key<T: ::wasm_bindgen::JsGeneric>(this: &EvaluationDetails<T>) -> String;
    #[wasm_bindgen(method, setter, js_name = "flagKey")]
    pub fn set_flag_key<T: ::wasm_bindgen::JsGeneric>(this: &EvaluationDetails<T>, val: &str);
    #[wasm_bindgen(method, getter)]
    pub fn value<T: ::wasm_bindgen::JsGeneric>(this: &EvaluationDetails<T>) -> T;
    #[wasm_bindgen(method, setter)]
    pub fn set_value<T: ::wasm_bindgen::JsGeneric>(this: &EvaluationDetails<T>, val: &T);
    #[wasm_bindgen(method, getter)]
    pub fn variant<T: ::wasm_bindgen::JsGeneric>(this: &EvaluationDetails<T>) -> Option<String>;
    #[wasm_bindgen(method, setter)]
    pub fn set_variant<T: ::wasm_bindgen::JsGeneric>(this: &EvaluationDetails<T>, val: &str);
    #[wasm_bindgen(method, getter)]
    pub fn reason<T: ::wasm_bindgen::JsGeneric>(this: &EvaluationDetails<T>) -> Option<String>;
    #[wasm_bindgen(method, setter)]
    pub fn set_reason<T: ::wasm_bindgen::JsGeneric>(this: &EvaluationDetails<T>, val: &str);
}
impl<T: ::wasm_bindgen::JsGeneric> EvaluationDetails<T> {
    pub fn new(flag_key: &str, value: &T) -> EvaluationDetails<T> {
        Self::builder(flag_key, value).build()
    }
    pub fn builder(flag_key: &str, value: &T) -> EvaluationDetailsBuilder<T> {
        let inner: EvaluationDetails<T> = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_flag_key(flag_key);
        inner.set_value(value);
        EvaluationDetailsBuilder { inner }
    }
}
pub struct EvaluationDetailsBuilder<T: ::wasm_bindgen::JsGeneric> {
    inner: EvaluationDetails<T>,
}
impl<T: ::wasm_bindgen::JsGeneric> EvaluationDetailsBuilder<T> {
    pub fn variant(self, val: &str) -> Self {
        self.inner.set_variant(val);
        self
    }
    pub fn reason(self, val: &str) -> Self {
        self.inner.set_reason(val);
        self
    }
    pub fn build(self) -> EvaluationDetails<T> {
        self.inner
    }
}
