// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[allow(dead_code)]
pub type Id = JsString;
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type S;
    #[wasm_bindgen(method, getter)]
    pub fn x(this: &S) -> f64;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type S2;
    #[wasm_bindgen(method, getter)]
    pub fn x(this: &S2) -> f64;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "byAlias")]
    pub fn by_alias(id: impl ::wasm_bindgen::JsStringLike) -> String;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "byAlias")]
    pub fn by_alias_js_string(id: impl ::wasm_bindgen::JsStringLike) -> JsString;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "byAlias")]
    pub fn try_by_alias(id: impl ::wasm_bindgen::JsStringLike) -> Result<String, JsValue>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "byAlias")]
    pub fn try_by_alias_js_string(
        id: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<JsString, JsValue>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "asyncByAlias")]
    pub async fn async_by_alias(id: impl ::wasm_bindgen::JsStringLike) -> Result<String, JsValue>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "asyncByAlias")]
    pub async fn async_by_alias_js_string(
        id: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<JsString, JsValue>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "withS")]
    pub fn with_s(s: &S, s2: &S2, name: impl ::wasm_bindgen::JsStringLike);
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "withS")]
    pub fn try_with_s(
        s: &S,
        s2: &S2,
        name: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Holder<T>;
    #[wasm_bindgen(constructor, catch)]
    pub fn new<T>(value: T) -> Result<Holder<T>, JsValue>;
    #[wasm_bindgen(method)]
    pub fn get<T>(this: &Holder<T>) -> T;
    #[wasm_bindgen(method, catch, js_name = "get")]
    pub fn try_get<T>(this: &Holder<T>) -> Result<T, JsValue>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "takesHolder")]
    pub fn takes_holder(h: &Holder<String>, g: &Holder<String>);
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "takesHolder")]
    pub fn try_takes_holder(h: &Holder<String>, g: &Holder<String>) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "holderOfId")]
    pub fn holder_of_id() -> Holder<String>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "holderOfId")]
    pub fn holder_of_id_js_string() -> Holder<JsString>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "holderOfId")]
    pub fn try_holder_of_id() -> Result<Holder<String>, JsValue>;
}
#[wasm_bindgen(module = "generic-mono-review", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "holderOfId")]
    pub fn try_holder_of_id_js_string() -> Result<Holder<JsString>, JsValue>;
}
