// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type KeyValueStore;
    #[wasm_bindgen(method)]
    pub fn list<T: ::wasm_bindgen::JsGeneric>(this: &KeyValueStore) -> KeyValueStoreList<T>;
    #[wasm_bindgen(method, catch, js_name = "list")]
    pub fn try_list<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStore,
    ) -> Result<KeyValueStoreList<T>, JsValue>;
    #[wasm_bindgen(method, js_name = "listAsync")]
    pub fn list_async<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStore,
    ) -> KeyValueStoreListAsync<T>;
    #[wasm_bindgen(method, catch, js_name = "listAsync")]
    pub fn try_list_async<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStore,
    ) -> Result<KeyValueStoreListAsync<T>, JsValue>;
    #[wasm_bindgen(method)]
    pub fn entries<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStore,
    ) -> Iterator<ArrayTuple<(JsString, T)>>;
    #[wasm_bindgen(method, catch, js_name = "entries")]
    pub fn try_entries<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStore,
    ) -> Result<Iterator<ArrayTuple<(JsString, T)>>, JsValue>;
    #[wasm_bindgen(method)]
    pub fn keys(this: &KeyValueStore) -> Iterator<JsString>;
    #[wasm_bindgen(method, catch, js_name = "keys")]
    pub fn try_keys(this: &KeyValueStore) -> Result<Iterator<JsString>, JsValue>;
    #[wasm_bindgen(method)]
    pub fn pages<T: ::wasm_bindgen::JsGeneric>(this: &KeyValueStore) -> AsyncIterator<T>;
    #[wasm_bindgen(method, catch, js_name = "pages")]
    pub fn try_pages<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStore,
    ) -> Result<AsyncIterator<T>, JsValue>;
    #[wasm_bindgen(method, js_name = "asyncEntries")]
    pub fn async_entries<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStore,
    ) -> AsyncIterator<ArrayTuple<(JsString, T)>>;
    #[wasm_bindgen(method, catch, js_name = "asyncEntries")]
    pub fn try_async_entries<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStore,
    ) -> Result<AsyncIterator<ArrayTuple<(JsString, T)>>, JsValue>;
    #[wasm_bindgen(method)]
    pub fn put<T: ::wasm_bindgen::JsGeneric>(this: &KeyValueStore, key: &str, value: &T);
    #[wasm_bindgen(method, catch, js_name = "put")]
    pub fn try_put<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStore,
        key: &str,
        value: &T,
    ) -> Result<(), JsValue>;
    #[wasm_bindgen(method)]
    pub fn get<T: ::wasm_bindgen::JsGeneric>(this: &KeyValueStore, key: &str) -> Option<T>;
    #[wasm_bindgen(method, catch, js_name = "get")]
    pub fn try_get<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStore,
        key: &str,
    ) -> Result<Option<T>, JsValue>;
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type KeyValueStoreList<T: ::wasm_bindgen::JsGeneric>;
    #[doc = " Conformance to the JS iteration protocol — returns the underlying iterator."]
    #[wasm_bindgen(method, js_name = "[Symbol.iterator]")]
    pub fn iterator<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStoreList<T>,
    ) -> Iterator<ArrayTuple<(JsString, T)>>;
    #[doc = " Conformance to the JS iteration protocol — returns the underlying iterator."]
    #[wasm_bindgen(method, catch, js_name = "[Symbol.iterator]")]
    pub fn try_iterator<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStoreList<T>,
    ) -> Result<Iterator<ArrayTuple<(JsString, T)>>, JsValue>;
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type KeyValueStoreListAsync<T: ::wasm_bindgen::JsGeneric>;
    #[doc = " Conformance to the JS async iteration protocol — returns the underlying iterator."]
    #[wasm_bindgen(method, js_name = "[Symbol.asyncIterator]")]
    pub fn async_iterator<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStoreListAsync<T>,
    ) -> AsyncIterator<ArrayTuple<(JsString, T)>>;
    #[doc = " Conformance to the JS async iteration protocol — returns the underlying iterator."]
    #[wasm_bindgen(method, catch, js_name = "[Symbol.asyncIterator]")]
    pub fn try_async_iterator<T: ::wasm_bindgen::JsGeneric>(
        this: &KeyValueStoreListAsync<T>,
    ) -> Result<AsyncIterator<ArrayTuple<(JsString, T)>>, JsValue>;
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Cursor;
    #[wasm_bindgen(method)]
    pub fn walk<T: ::wasm_bindgen::JsGeneric>(this: &Cursor) -> CursorWalk<T>;
    #[wasm_bindgen(method, catch, js_name = "walk")]
    pub fn try_walk<T: ::wasm_bindgen::JsGeneric>(this: &Cursor) -> Result<CursorWalk<T>, JsValue>;
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type CursorWalk<T: ::wasm_bindgen::JsGeneric>;
    #[doc = " Conformance to the JS iteration protocol — returns the underlying iterator."]
    #[wasm_bindgen(method, js_name = "[Symbol.iterator]")]
    pub fn iterator<T: ::wasm_bindgen::JsGeneric>(this: &CursorWalk<T>) -> Iterator<T>;
    #[doc = " Conformance to the JS iteration protocol — returns the underlying iterator."]
    #[wasm_bindgen(method, catch, js_name = "[Symbol.iterator]")]
    pub fn try_iterator<T: ::wasm_bindgen::JsGeneric>(
        this: &CursorWalk<T>,
    ) -> Result<Iterator<T>, JsValue>;
}
