// Generated by ts-gen. Do not edit.

#[allow(dead_code)]
use ::other::foo::Bar;
#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type UsesBar;
    #[wasm_bindgen(method)]
    pub fn method(this: &UsesBar, b: &Bar);
    #[wasm_bindgen(method, catch, js_name = "method")]
    pub fn try_method(this: &UsesBar, b: &Bar) -> Result<(), JsValue>;
}
