// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen(module = "x:foo")]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Bar;
    #[wasm_bindgen(constructor, catch)]
    pub fn new(name: &str) -> Result<Bar, JsValue>;
    #[wasm_bindgen(method)]
    pub fn name(this: &Bar) -> String;
    #[wasm_bindgen(method, catch, js_name = "name")]
    pub fn try_name(this: &Bar) -> Result<String, JsValue>;
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type UsesBar;
    #[wasm_bindgen(method)]
    pub fn method(this: &UsesBar, b: &Bar);
    #[wasm_bindgen(method, catch, js_name = "method")]
    pub fn try_method(this: &UsesBar, b: &Bar) -> Result<(), JsValue>;
}
