// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "setValue")]
    pub fn set_value(value: impl ::js_sys::JsNumberOrStringLike);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setValue")]
    pub fn try_set_value(value: impl ::js_sys::JsNumberOrStringLike) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "setFlag")]
    pub fn set_flag(value: impl ::js_sys::JsBigIntOrBooleanLike);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setFlag")]
    pub fn try_set_flag(value: impl ::js_sys::JsBigIntOrBooleanLike) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "setAny")]
    pub fn set_any(value: impl ::js_sys::JsBigIntOrBooleanOrNumberOrStringLike);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setAny")]
    pub fn try_set_any(
        value: impl ::js_sys::JsBigIntOrBooleanOrNumberOrStringLike,
    ) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "setAny")]
    pub fn set_any_with_symbol(value: &Symbol);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setAny")]
    pub fn try_set_any_with_symbol(value: &Symbol) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "setKeyed")]
    pub fn set_keyed(value: impl ::wasm_bindgen::JsStringLike);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setKeyed")]
    pub fn try_set_keyed(value: impl ::wasm_bindgen::JsStringLike) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "setKeyed")]
    pub fn set_keyed_with_symbol(value: &Symbol);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setKeyed")]
    pub fn try_set_keyed_with_symbol(value: &Symbol) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "setLevel")]
    pub fn set_level(level: impl ::js_sys::JsNumberOrStringLike);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setLevel")]
    pub fn try_set_level(level: impl ::js_sys::JsNumberOrStringLike) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "setNullable")]
    pub fn set_nullable(value: impl ::js_sys::JsNumberOrStringLike);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setNullable")]
    pub fn try_set_nullable(value: impl ::js_sys::JsNumberOrStringLike) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "setMaybe")]
    pub fn set_maybe();
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setMaybe")]
    pub fn try_set_maybe() -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "setMaybe")]
    pub fn set_maybe_with_value(value: impl ::js_sys::JsNumberOrStringLike);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setMaybe")]
    pub fn try_set_maybe_with_value(
        value: impl ::js_sys::JsNumberOrStringLike,
    ) -> Result<(), JsValue>;
}
#[allow(dead_code)]
pub type Id = JsValue;
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    pub fn lookup(id: impl ::js_sys::JsNumberOrStringLike);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "lookup")]
    pub fn try_lookup(id: impl ::js_sys::JsNumberOrStringLike) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "hasKey")]
    pub fn has_key(key: impl ::js_sys::PropertyKey) -> bool;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "hasKey")]
    pub fn try_has_key(key: impl ::js_sys::PropertyKey) -> Result<bool, JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "hasKeyExplicit")]
    pub fn has_key_explicit(key: impl ::js_sys::PropertyKey) -> bool;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "hasKeyExplicit")]
    pub fn try_has_key_explicit(key: impl ::js_sys::PropertyKey) -> Result<bool, JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Target;
    #[wasm_bindgen(method, getter)]
    pub fn name(this: &Target) -> String;
    #[wasm_bindgen(method, getter, js_name = "name")]
    pub fn name_js_string(this: &Target) -> JsString;
    #[wasm_bindgen(method, setter)]
    pub fn set_name(this: &Target, val: impl ::wasm_bindgen::JsStringLike);
}
impl Target {
    pub fn new(name: impl ::wasm_bindgen::JsStringLike) -> Target {
        let inner: Target = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_name(name);
        inner
    }
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    pub fn send(to: &Target);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "send")]
    pub fn try_send(to: &Target) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "send")]
    pub fn send_with_number_or_string(to: impl ::js_sys::JsNumberOrStringLike);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "send")]
    pub fn try_send_with_number_or_string(
        to: impl ::js_sys::JsNumberOrStringLike,
    ) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "setMode")]
    pub fn set_mode(mode: impl ::wasm_bindgen::JsStringLike);
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setMode")]
    pub fn try_set_mode(mode: impl ::wasm_bindgen::JsStringLike) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    pub fn current() -> CurrentReturnKind;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "current")]
    pub fn try_current() -> Result<CurrentReturnKind, JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Store;
    #[wasm_bindgen(constructor, catch)]
    pub fn new(key: impl ::js_sys::PropertyKey) -> Result<Store, JsValue>;
    #[wasm_bindgen(method)]
    pub fn get(this: &Store, key: impl ::js_sys::JsNumberOrStringLike) -> String;
    #[wasm_bindgen(method, js_name = "get")]
    pub fn get_js_string(this: &Store, key: impl ::js_sys::JsNumberOrStringLike) -> JsString;
    #[wasm_bindgen(method, catch, js_name = "get")]
    pub fn try_get(
        this: &Store,
        key: impl ::js_sys::JsNumberOrStringLike,
    ) -> Result<String, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "get")]
    pub fn try_get_js_string(
        this: &Store,
        key: impl ::js_sys::JsNumberOrStringLike,
    ) -> Result<JsString, JsValue>;
    # [wasm_bindgen (static_method_of = Store)]
    pub fn of(value: impl ::js_sys::JsBooleanOrNumberLike) -> Store;
    # [wasm_bindgen (static_method_of = Store , catch , js_name = "of")]
    pub fn try_of(value: impl ::js_sys::JsBooleanOrNumberLike) -> Result<Store, JsValue>;
}
#[wasm_bindgen(module = "primitive-unions-mono", experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Settings;
    #[wasm_bindgen(method, getter)]
    pub fn level(this: &Settings) -> LevelKind;
    #[wasm_bindgen(method, setter)]
    pub fn set_level(this: &Settings, val: impl ::js_sys::JsNumberOrStringLike);
    #[wasm_bindgen(method, getter)]
    pub fn id(this: &Settings) -> CurrentReturnKind;
    #[wasm_bindgen(method, setter)]
    pub fn set_id(this: &Settings, val: impl ::js_sys::JsNumberOrStringLike);
    #[wasm_bindgen(method, getter)]
    pub fn label(this: &Settings) -> Option<LabelKind>;
    #[wasm_bindgen(method, setter)]
    pub fn set_label(this: &Settings, val: impl ::js_sys::JsBooleanOrStringLike);
    #[wasm_bindgen(method, getter)]
    pub fn from(this: &Settings) -> FromKind;
    #[wasm_bindgen(method, setter)]
    pub fn set_from(this: &Settings, val: &Target);
    #[wasm_bindgen(method, setter, js_name = "from")]
    pub fn set_from_with_boolean_or_string(
        this: &Settings,
        val: impl ::js_sys::JsBooleanOrStringLike,
    );
}
impl Settings {
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `level: \"low\"`"]
    pub fn new_low(id: impl ::js_sys::JsNumberOrStringLike, from: &Target) -> Settings {
        Self::builder_low(id, from).build()
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `level: \"low\"`"]
    pub fn new_low_with_boolean_or_string(
        id: impl ::js_sys::JsNumberOrStringLike,
        from: impl ::js_sys::JsBooleanOrStringLike,
    ) -> Settings {
        Self::builder_low_with_boolean_or_string(id, from).build()
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `level: \"high\"`"]
    pub fn new_high(id: impl ::js_sys::JsNumberOrStringLike, from: &Target) -> Settings {
        Self::builder_high(id, from).build()
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `level: \"high\"`"]
    pub fn new_high_with_boolean_or_string(
        id: impl ::js_sys::JsNumberOrStringLike,
        from: impl ::js_sys::JsBooleanOrStringLike,
    ) -> Settings {
        Self::builder_high_with_boolean_or_string(id, from).build()
    }
    pub fn new(level: f64, id: impl ::js_sys::JsNumberOrStringLike, from: &Target) -> Settings {
        Self::builder(level, id, from).build()
    }
    pub fn new_with_boolean_or_string(
        level: f64,
        id: impl ::js_sys::JsNumberOrStringLike,
        from: impl ::js_sys::JsBooleanOrStringLike,
    ) -> Settings {
        Self::builder_with_boolean_or_string(level, id, from).build()
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `level: \"low\"`"]
    pub fn builder_low(id: impl ::js_sys::JsNumberOrStringLike, from: &Target) -> SettingsBuilder {
        let inner: Settings = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_level("low");
        inner.set_id(id);
        inner.set_from(from);
        SettingsBuilder { inner }
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `level: \"low\"`"]
    pub fn builder_low_with_boolean_or_string(
        id: impl ::js_sys::JsNumberOrStringLike,
        from: impl ::js_sys::JsBooleanOrStringLike,
    ) -> SettingsBuilder {
        let inner: Settings = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_level("low");
        inner.set_id(id);
        inner.set_from_with_boolean_or_string(from);
        SettingsBuilder { inner }
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `level: \"high\"`"]
    pub fn builder_high(id: impl ::js_sys::JsNumberOrStringLike, from: &Target) -> SettingsBuilder {
        let inner: Settings = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_level("high");
        inner.set_id(id);
        inner.set_from(from);
        SettingsBuilder { inner }
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `level: \"high\"`"]
    pub fn builder_high_with_boolean_or_string(
        id: impl ::js_sys::JsNumberOrStringLike,
        from: impl ::js_sys::JsBooleanOrStringLike,
    ) -> SettingsBuilder {
        let inner: Settings = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_level("high");
        inner.set_id(id);
        inner.set_from_with_boolean_or_string(from);
        SettingsBuilder { inner }
    }
    pub fn builder(
        level: f64,
        id: impl ::js_sys::JsNumberOrStringLike,
        from: &Target,
    ) -> SettingsBuilder {
        let inner: Settings = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_level(level);
        inner.set_id(id);
        inner.set_from(from);
        SettingsBuilder { inner }
    }
    pub fn builder_with_boolean_or_string(
        level: f64,
        id: impl ::js_sys::JsNumberOrStringLike,
        from: impl ::js_sys::JsBooleanOrStringLike,
    ) -> SettingsBuilder {
        let inner: Settings = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_level(level);
        inner.set_id(id);
        inner.set_from_with_boolean_or_string(from);
        SettingsBuilder { inner }
    }
}
pub struct SettingsBuilder {
    inner: Settings,
}
impl SettingsBuilder {
    pub fn label(self, val: impl ::js_sys::JsBooleanOrStringLike) -> Self {
        self.inner.set_label(val);
        self
    }
    pub fn build(self) -> Settings {
        self.inner
    }
}
#[wasm_bindgen]
pub enum CurrentReturnKind {
    String(String),
    F64(f64),
}
#[wasm_bindgen]
pub enum LevelKind {
    Low = "low",
    High = "high",
    F64(f64),
}
#[wasm_bindgen]
pub enum LabelKind {
    String(String),
    Bool(bool),
}
#[wasm_bindgen]
pub enum FromKind {
    Target(Target),
    String(String),
    Bool(bool),
}
