// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(js_name = "hasKey")]
    pub fn has_key(key: &str) -> bool;
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "hasKey")]
    pub fn try_has_key(key: &str) -> Result<bool, JsValue>;
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(js_name = "hasKey")]
    pub fn has_key_with_f64(key: f64) -> bool;
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "hasKey")]
    pub fn try_has_key_with_f64(key: f64) -> Result<bool, JsValue>;
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(js_name = "hasKey")]
    pub fn has_key_with_js_value(key: &JsValue) -> bool;
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "hasKey")]
    pub fn try_has_key_with_js_value(key: &JsValue) -> Result<bool, JsValue>;
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(js_name = "firstKey")]
    pub fn first_key() -> FirstKeyReturnKind;
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "firstKey")]
    pub fn try_first_key() -> Result<FirstKeyReturnKind, JsValue>;
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    pub fn keys() -> Vec<JsValue>;
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "keys")]
    pub fn try_keys() -> Result<Vec<JsValue>, JsValue>;
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(js_name = "setValue")]
    pub fn set_value(value: &str);
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setValue")]
    pub fn try_set_value(value: &str) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(js_name = "setValue")]
    pub fn set_value_with_f64(value: f64);
}
#[wasm_bindgen(module = "property-key")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setValue")]
    pub fn try_set_value_with_f64(value: f64) -> Result<(), JsValue>;
}
#[wasm_bindgen]
pub enum FirstKeyReturnKind {
    String(String),
    F64(f64),
    JsValue(JsValue),
}
