// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type EvaluationContext;
    #[wasm_bindgen(catch, method, indexing_setter)]
    pub fn set_string(
        this: &EvaluationContext,
        key: impl ::wasm_bindgen::JsStringLike,
        value: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<(), JsValue>;
    #[wasm_bindgen(catch, method, indexing_setter)]
    pub fn set_number(
        this: &EvaluationContext,
        key: impl ::wasm_bindgen::JsStringLike,
        value: f64,
    ) -> Result<(), JsValue>;
    #[wasm_bindgen(catch, method, indexing_setter)]
    pub fn set_bool(
        this: &EvaluationContext,
        key: impl ::wasm_bindgen::JsStringLike,
        value: bool,
    ) -> Result<(), JsValue>;
}
impl EvaluationContext {
    #[allow(clippy::new_without_default)]
    pub fn new() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Labels;
    #[wasm_bindgen(catch, method, indexing_setter)]
    pub fn set(
        this: &Labels,
        key: impl ::wasm_bindgen::JsStringLike,
        value: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<(), JsValue>;
}
impl Labels {
    #[allow(clippy::new_without_default)]
    pub fn new() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Values<T>;
    #[wasm_bindgen(catch, method, indexing_setter)]
    pub fn set<T>(
        this: &Values<T>,
        key: impl ::wasm_bindgen::JsStringLike,
        value: T,
    ) -> Result<(), JsValue>;
}
impl<T> Values<T> {
    #[allow(clippy::new_without_default)]
    pub fn new() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type MixedValues;
    #[wasm_bindgen(catch, method, indexing_setter)]
    pub fn set_string(
        this: &MixedValues,
        key: impl ::wasm_bindgen::JsStringLike,
        value: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<(), JsValue>;
    #[wasm_bindgen(catch, method, indexing_setter, slice_to_array)]
    pub fn set_slice(
        this: &MixedValues,
        key: impl ::wasm_bindgen::JsStringLike,
        value: &[String],
    ) -> Result<(), JsValue>;
}
impl MixedValues {
    #[allow(clippy::new_without_default)]
    pub fn new() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    pub fn evaluate(context: &EvaluationContext);
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "evaluate")]
    pub fn try_evaluate(context: &EvaluationContext) -> Result<(), JsValue>;
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "labelAll")]
    pub fn label_all(labels: &Labels);
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "labelAll")]
    pub fn try_label_all(labels: &Labels) -> Result<(), JsValue>;
}
