// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type EvaluationContext;
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get_string(this: &EvaluationContext, key: impl ::wasm_bindgen::JsStringLike) -> String;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get_string(
        this: &EvaluationContext,
        key: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<String, JsValue>;
    #[wasm_bindgen(method, indexing_setter)]
    pub fn set_string(
        this: &EvaluationContext,
        key: impl ::wasm_bindgen::JsStringLike,
        value: impl ::wasm_bindgen::JsStringLike,
    );
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get_number(this: &EvaluationContext, key: impl ::wasm_bindgen::JsStringLike) -> f64;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get_number(
        this: &EvaluationContext,
        key: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<f64, JsValue>;
    #[wasm_bindgen(method, indexing_setter)]
    pub fn set_number(this: &EvaluationContext, key: impl ::wasm_bindgen::JsStringLike, value: f64);
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get_bool(this: &EvaluationContext, key: impl ::wasm_bindgen::JsStringLike) -> bool;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get_bool(
        this: &EvaluationContext,
        key: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<bool, JsValue>;
    #[wasm_bindgen(method, indexing_setter)]
    pub fn set_bool(this: &EvaluationContext, key: impl ::wasm_bindgen::JsStringLike, value: bool);
}
impl Default for EvaluationContext {
    fn default() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
impl EvaluationContext {
    pub fn new() -> Self {
        Self::default()
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Labels;
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get(this: &Labels, key: impl ::wasm_bindgen::JsStringLike) -> String;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get(
        this: &Labels,
        key: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<String, JsValue>;
    #[wasm_bindgen(method, indexing_setter)]
    pub fn set(
        this: &Labels,
        key: impl ::wasm_bindgen::JsStringLike,
        value: impl ::wasm_bindgen::JsStringLike,
    );
}
impl Default for Labels {
    fn default() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
impl Labels {
    pub fn new() -> Self {
        Self::default()
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Values<T>;
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get<T>(this: &Values<T>, key: impl ::wasm_bindgen::JsStringLike) -> T;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get<T>(
        this: &Values<T>,
        key: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<T, JsValue>;
    #[wasm_bindgen(method, indexing_setter)]
    pub fn set<T>(this: &Values<T>, key: impl ::wasm_bindgen::JsStringLike, value: T);
}
impl<T> Default for Values<T> {
    fn default() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
impl<T> Values<T> {
    pub fn new() -> Self {
        Self::default()
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type MixedValues;
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get_string(this: &MixedValues, key: impl ::wasm_bindgen::JsStringLike) -> String;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get_string(
        this: &MixedValues,
        key: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<String, JsValue>;
    #[wasm_bindgen(method, indexing_setter)]
    pub fn set_string(
        this: &MixedValues,
        key: impl ::wasm_bindgen::JsStringLike,
        value: impl ::wasm_bindgen::JsStringLike,
    );
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get_slice_of_string(
        this: &MixedValues,
        key: impl ::wasm_bindgen::JsStringLike,
    ) -> Vec<String>;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get_slice_of_string(
        this: &MixedValues,
        key: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<Vec<String>, JsValue>;
    #[wasm_bindgen(method, indexing_setter, slice_to_array)]
    pub fn set_slice_of_string(
        this: &MixedValues,
        key: impl ::wasm_bindgen::JsStringLike,
        value: &[String],
    );
}
impl Default for MixedValues {
    fn default() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
impl MixedValues {
    pub fn new() -> Self {
        Self::default()
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Colors;
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get(this: &Colors, key: impl ::wasm_bindgen::JsStringLike) -> String;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get(
        this: &Colors,
        key: impl ::wasm_bindgen::JsStringLike,
    ) -> Result<String, JsValue>;
    #[wasm_bindgen(method, indexing_setter)]
    pub fn set(
        this: &Colors,
        key: impl ::wasm_bindgen::JsStringLike,
        value: impl ::wasm_bindgen::JsStringLike,
    );
}
impl Default for Colors {
    fn default() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
impl Colors {
    pub fn new() -> Self {
        Self::default()
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type NumericLabels;
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get(this: &NumericLabels, key: f64) -> String;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get(this: &NumericLabels, key: f64) -> Result<String, JsValue>;
    #[wasm_bindgen(method, indexing_setter)]
    pub fn set(this: &NumericLabels, key: f64, value: impl ::wasm_bindgen::JsStringLike);
}
impl Default for NumericLabels {
    fn default() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
impl NumericLabels {
    pub fn new() -> Self {
        Self::default()
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type FlexibleRecord;
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get_string(this: &FlexibleRecord, key: &JsValue) -> String;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get_string(this: &FlexibleRecord, key: &JsValue) -> Result<String, JsValue>;
    #[wasm_bindgen(method, indexing_setter)]
    pub fn set_string(
        this: &FlexibleRecord,
        key: &JsValue,
        value: impl ::wasm_bindgen::JsStringLike,
    );
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get_bool(this: &FlexibleRecord, key: &JsValue) -> bool;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get_bool(this: &FlexibleRecord, key: &JsValue) -> Result<bool, JsValue>;
    #[wasm_bindgen(method, indexing_setter)]
    pub fn set_bool(this: &FlexibleRecord, key: &JsValue, value: bool);
}
impl Default for FlexibleRecord {
    fn default() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
impl FlexibleRecord {
    pub fn new() -> Self {
        Self::default()
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type OpenKeyFlags;
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get(this: &OpenKeyFlags, key: &JsValue) -> bool;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get(this: &OpenKeyFlags, key: &JsValue) -> Result<bool, JsValue>;
    #[wasm_bindgen(method, indexing_setter)]
    pub fn set(this: &OpenKeyFlags, key: &JsValue, value: bool);
}
impl Default for OpenKeyFlags {
    fn default() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
impl OpenKeyFlags {
    pub fn new() -> Self {
        Self::default()
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type KnownLabels;
    #[wasm_bindgen(method, indexing_getter)]
    pub fn get(this: &KnownLabels, key: &JsValue) -> String;
    #[wasm_bindgen(catch, method, indexing_getter)]
    pub fn try_get(this: &KnownLabels, key: &JsValue) -> Result<String, JsValue>;
    #[wasm_bindgen(method, indexing_setter)]
    pub fn set(this: &KnownLabels, key: &JsValue, value: impl ::wasm_bindgen::JsStringLike);
}
impl Default for KnownLabels {
    fn default() -> Self {
        JsCast::unchecked_into(js_sys::Object::new())
    }
}
impl KnownLabels {
    pub fn new() -> Self {
        Self::default()
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    pub fn evaluate(context: &EvaluationContext);
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "evaluate")]
    pub fn try_evaluate(context: &EvaluationContext) -> Result<(), JsValue>;
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(js_name = "labelAll")]
    pub fn label_all(labels: &Labels);
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    #[wasm_bindgen(catch, js_name = "labelAll")]
    pub fn try_label_all(labels: &Labels) -> Result<(), JsValue>;
}
