// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Color {
    Red = "red",
    Green = "green",
    Blue = "blue",
}
#[wasm_bindgen(module = "string-enum-union")]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Style;
    #[wasm_bindgen(method, getter)]
    pub fn tint(this: &Style) -> TintKind;
    #[wasm_bindgen(method, getter)]
    pub fn fill(this: &Style) -> FillKind;
}
impl Style {
    #[allow(clippy::new_without_default)]
    pub fn new() -> Style {
        #[allow(unused_unsafe)]
        unsafe {
            JsValue::from(js_sys::Object::new()).unchecked_into()
        }
    }
}
#[wasm_bindgen]
pub enum TintKind {
    JsString(JsString),
    Transparent = "transparent",
}
#[wasm_bindgen]
pub enum FillKind {
    Bool(bool),
    JsString(JsString),
}
