// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen(module = "symbol")]
extern "C" {
    pub fn describe(value: &Symbol) -> String;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "describe")]
    pub fn try_describe(value: &Symbol) -> Result<String, JsValue>;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    pub fn create() -> Symbol;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "create")]
    pub fn try_create() -> Result<Symbol, JsValue>;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(js_name = "create")]
    pub fn create_with_description(description: &str) -> Symbol;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "create")]
    pub fn try_create_with_description(description: &str) -> Result<Symbol, JsValue>;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    pub fn find(name: &str) -> Option<Symbol>;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "find")]
    pub fn try_find(name: &str) -> Result<Option<Symbol>, JsValue>;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    pub fn all() -> Vec<Symbol>;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "all")]
    pub fn try_all() -> Result<Vec<Symbol>, JsValue>;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(js_name = "forEach")]
    pub fn for_each(callback: &Function<fn(Symbol) -> Undefined>);
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "forEach")]
    pub fn try_for_each(callback: &Function<fn(Symbol) -> Undefined>) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(js_name = "setKey")]
    pub fn set_key(key: &str);
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setKey")]
    pub fn try_set_key(key: &str) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(js_name = "setKey")]
    pub fn set_key_with_symbol(key: &Symbol);
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "setKey")]
    pub fn try_set_key_with_symbol(key: &Symbol) -> Result<(), JsValue>;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    pub fn lookup() -> LookupReturnKind;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    #[wasm_bindgen(catch, js_name = "lookup")]
    pub fn try_lookup() -> Result<LookupReturnKind, JsValue>;
}
#[wasm_bindgen(module = "symbol")]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Tagged;
    #[wasm_bindgen(method, getter)]
    pub fn tag(this: &Tagged) -> Symbol;
    #[wasm_bindgen(method, setter)]
    pub fn set_tag(this: &Tagged, val: &Symbol);
    #[wasm_bindgen(method, getter)]
    pub fn alias(this: &Tagged) -> Option<Symbol>;
    #[wasm_bindgen(method, setter)]
    pub fn set_alias(this: &Tagged, val: &Symbol);
}
impl Tagged {
    pub fn new(tag: &Symbol) -> Tagged {
        Self::builder(tag).build()
    }
    pub fn builder(tag: &Symbol) -> TaggedBuilder {
        let inner: Tagged = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_tag(tag);
        TaggedBuilder { inner }
    }
}
pub struct TaggedBuilder {
    inner: Tagged,
}
impl TaggedBuilder {
    pub fn alias(self, val: &Symbol) -> Self {
        self.inner.set_alias(val);
        self
    }
    pub fn build(self) -> Tagged {
        self.inner
    }
}
#[wasm_bindgen]
pub enum LookupReturnKind {
    String(String),
    Symbol(Symbol),
}
